### PR TITLE
Fix PM benchmarks

### LINKED ISSUE #195: Rearrange benchmarks taking into account the new `Court` pallet

### PR DESCRIPTION
**Pull request by c410-f3r**
Fixes #195

### CODE REVIEW

File: zrml/simple-disputes/src/lib.rs [hunk 1]
```diff
@@ -302,14 +419,16 @@ mod pallet {
             }
 
             Self::deposit_event(Event::MarketDisputed(market_id, outcome));
-            Self::calculate_actual_weight(|_| 0, num_disputes as u32, max_disputes as u32)
+            calculate_actual_weight(|_| 0, num_disputes as u32, max_disputes as u32)
```
Comment (sea212) [inline zrml/simple-disputes/src/lib.rs:422]: I am confused about this return value. It doesn't seem to be used anywhere, in fact the whole `on_dispute` function is only called during the setup of benchmarks in the PM pallet, in fuzz and in tests. Will this return value ever be used anywhere? If it will, it must be changed because currently it always implies a weight correction to 0 weight when `num_disputes != max_disputes`

**Review by sea212 — APPROVED** [review]

File: zrml/simple-disputes/src/lib.rs (hunk 1 above)
Comment (c410-f3r) [reply zrml/simple-disputes/src/lib.rs]: Hum... Totally missed this one, thanks for spotting it.

`on_dispute` was a PM call, thus the reason of `calculate_actual_weight`.

File: zrml/prediction-markets/src/lib.rs [hunk 2]
```diff
@@ -279,6 +280,16 @@ mod pallet {
...
+        #[pallet::weight(T::WeightInfo::dispute(T::SimpleDisputes::max_disputes()))]
+        pub fn dispute(
+            origin: OriginFor<T>,
+            market_id: MarketIdOf<T>,
+            outcome: OutcomeReport,
+        ) -> DispatchResultWithPostInfo {
+            let [weight, max_weight] = T::SimpleDisputes::on_dispute(origin, market_id, outcome)?;
+            Self::calculate_actual_weight(&T::WeightInfo::dispute, weight, max_weight)
+        }
+
```
Comment (c410-f3r) [inline zrml/prediction-markets/src/lib.rs:292]: @lsaether Re-adding this call until the actual court pallet is implemented

Comment (lsaether) [reply zrml/prediction-markets/src/lib.rs:292]: I actually think we should keep this like this, then pattern match on the `DisputeMechanism` for the `market_id` and route the call to either `SimpleDisputes` or `Court` based on what's configured.

Comment (c410-f3r) [reply zrml/prediction-markets/src/lib.rs:292]: Got it!

**Review by lsaether — APPROVED** [review]
